version: '3'

networks:
  backend:

services:
  bootstrap:
    build: ./docker/bootstrap
    command: ./docker/bootstrap/start
    working_dir: /opt/moviedownloader
    volumes:
      - .:/opt/moviedownloader
    networks:
      - backend
  moviedownloader:
    build: ./docker/moviedownloader
    command: php artisan movie:download
    working_dir: /opt/moviedownloader
    volumes:
      - .:/opt/moviedownloader
    depends_on:
      - bootstrap
      - redis
    networks:
      - backend
  downloadchecker:
    build: ./docker/downloadchecker
    command: php artisan download:check
    working_dir: /opt/moviedownloader
    volumes:
      - .:/opt/moviedownloader
      - /home/gustavo/test:/data/movies
    depends_on:
      - bootstrap
      - redis
      - transmission
    networks:
      - backend
  redis:
    image: redis:3.2.8-alpine
    networks:
      - backend
  worker:
    build: ./docker/worker
    command: php artisan queue:work --tries=3
    working_dir: /opt/moviedownloader
    volumes:
      - .:/opt/moviedownloader
    depends_on:
      - bootstrap
      - redis
    networks:
      - backend
  transmission:
    image: rlesouef/alpine-transmission:latest
    volumes:
      - /home/gustavo/test:/data/movies
    depends_on:
      - moviedownloader
    networks:
      - backend
